Website/app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import current_user, login_user, logout_user, login_required
from app.main.forms import ContactForm, FAQForm, DeleteQuestionForm, \
    EditQuestionForm, PostForm, EditPostForm, TradeInForm, SellDetailsForm, \
    CheckoutDetailsForm, InsuranceForm, ReviewForm
from app.models import User, FAQ, Post, Vehicles, Model, Make, Trade, Insurance, CarReview, History
from sqlalchemy.sql import func, or_
from app.funcs import save_picture
from app import db

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/index', methods=['GET', 'POST'])
def index():
    cars_for_render = Vehicles.query.order_by(Vehicles.id.asc())
    makes_for_render = Make.query.order_by(Make.make_id.asc())
    models_for_render = Model.query.order_by(Model.model_id.asc())
    posts_for_render = Post.query.order_by(Post.created_at.asc())
    return render_template('index.html', posts=posts_for_render, cars=cars_for_render, makes=makes_for_render, models=models_for_render, title='Home')


@main.route('/ContactUs', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        flash('Your message has been sent to our team', 'success')

        return redirect(url_for('main.contact'))
    return render_template('contact.html', title='Contact Us', form=form)


@main.route('/FAQ', methods=['GET', 'POST'])
def FAQs():
    questions_for_render = FAQ.query.order_by(FAQ.id.asc())
    form = FAQForm()
    if form.validate_on_submit():
        q = FAQ(
            name=form.name.data,
            question=form.question.data,
        )
        db.session.add(q)
        db.session.commit()
    return render_template('FAQ/questions.html', questions=questions_for_render, form=form, title='FAQ')


@main.route('/FAQ/view_all', methods=['GET', 'POST'])
def viewAllQuestions():
    question = FAQ.query.order_by(FAQ.id.asc())
    return render_template('FAQ/view_all.html', questions=question, title='view')


@main.route('/FAQ/view_all/vis<id>', methods=['GET', 'POST'])
@login_required
def changeVisibility(id):
    question = FAQ.query.get(id)
    if question.display == 1:
        question.display = 0
        db.session.commit()
        return redirect(url_for('main.FAQs'))
    if question.display == 0:
        question.display = 1
        db.session.commit()
        return redirect(url_for('main.FAQs'))
    return render_template('FAQ/questions.html')


@main.route('/FAQ/delete_question/<id>', methods=['GET', 'POST'])
@login_required
def delQuestion(id):
    question = FAQ.query.get(id)
    form = DeleteQuestionForm()
    if request.method == 'POST' and form.delete.data:
        db.session.delete(question)
        db.session.commit()
        flash('Question was deleted successfuly', 'success')
        return redirect(url_for('main.FAQs'))
    if form.cancel.data:
        return redirect(url_for('main.FAQs'))
    return render_template('FAQ/delete_question.html', question=question, title="Delete Question", form=form)


@main.route('/FAQ/edit_question/<id>', methods=['GET', 'POST'])
@login_required
def editQuestion(id):
    question = FAQ.query.get_or_404(id)
    form = EditQuestionForm()
    if request.method == 'GET':
        form.name.data = question.name
        form.question.data = question.question
        form.answer.data = question.answer
    elif request.method == 'POST':
        if form.update.data and form.validate_on_submit():
            question.name = request.form['name']
            question.question = request.form['question']
            question.answer = request.form['answer']
            db.session.commit()
            return(redirect(url_for('main.FAQs')))
        if form.cancel.data:
            return(redirect(url_for('main.FAQs')))
    return render_template('FAQ/edit_question.html',  question=question, title='Edit Question', form=form)


@main.route('/all_posts', methods=['GET', 'POST'])
def Blog():
    posts = Post.query.order_by(Post.id.asc())
    return render_template('blog/all_posts.html', posts=posts)


@main.route('/blog/post_page/<id>', methods=['GET', 'POST'])
def getPost(id):
    post = Post.query.get_or_404(id)
    return render_template('blog/post_page.html', post=post)


@main.route('/blog/new_post', methods=['GET', 'POST'])
@login_required
def newPost():
    form = PostForm()
    if form.validate_on_submit():
        picture = 'default.jpg'
        if form.picture.data:
            picture = save_picture(form.picture.data, 'static/post_pics')
        p = Post(
            title=form.title.data,
            caption=form.caption.data,
            picture=picture,
            user_id=current_user.get_id()
        )
        db.session.add(p)
        db.session.commit()
        return redirect(url_for('main.index'))
    if form.cancel.data:
        return redirect(url_for('main.index'))
    return render_template('blog/new_post.html', title='New Post', form=form)


@main.route('/blog/edit_post/<id>', methods=['GET', 'POST'])
@login_required
def editPost(id):
    post = Post.query.get_or_404(id)
    form = EditPostForm()
    if request.method == 'GET':
        form.title.data = post.title
        form.caption.data = post.caption
        form.picture.data = post.picture
    elif request.method == 'POST':
        if form.update.data and form.validate_on_submit():
            post.title = request.form['title']
            post.caption = request.form['caption']
            if form.picture.data:
                post.picture = save_picture(
                    form.picture.data, 'static/post_pics')
            db.session.commit()
            return(redirect(url_for('main.index')))
        if request.method == 'POST' and form.delete.data:
            db.session.delete(post)
            db.session.commit()
            return redirect(url_for('main.index'))
        if form.cancel.data:
            return(redirect(url_for('main.index')))
    return render_template('blog/edit_post.html',  post=post, title='Edit Post', form=form)


@main.route('/vehicle/<id>', methods=['GET', 'POST'])
def vehicle(id):
    vehicle_to_render = Vehicles.query.get(id)
    makes_for_render = Make.query.order_by(Make.make_id.asc())
    models_for_render = Model.query.order_by(Model.model_id.asc())
    history_for_render = History.query.order_by(History.history_id.asc())
    return render_template('vehicles/car_page.html', car=vehicle_to_render, makes=makes_for_render, models=models_for_render, history=history_for_render)


@main.route('/trade-in', methods=['GET', 'POST'])
@login_required
def trade_in():
    form = TradeInForm()
    #form.make.choices = Make.query.order_by(Make.make_id.asc())
    #form.model.choices = Model.query.order_by(Model.model_id.asc())
    if form.validate_on_submit():

        price = 1000  # use valuation to get price?

        make_exist = Make.query.filter(
            Make.make_name == form.make.data).first()
        if not make_exist:
            make_new = Make(
                make_name=form.make.data,
            )
            db.session.add(make_new)
            db.session.commit()

        newMake = Make.query.filter(Make.make_name == form.make.data).first()
        makeId = newMake.make_id

        model_exist = Model.query.filter(
            Model.model_name == form.model.data).first()
        if not model_exist:
            model_new = Model(
                model_name=form.model.data,
                make_id=makeId
            )
            db.session.add(model_new)
            db.session.commit()

        newModel = Model.query.filter(
            Model.model_name == form.model.data).first()
        modId = newModel.model_id

        picture_folder = str(form.model.data + '_' +
                             form.color.data + '_' + str(form.year.data))
        #filename_one = secure_filename(form.picture_one.data)
        #filename_two = secure_filename(form.picture_two.data)
        #filename_three = secure_filename(form.picture_three.data)
        #form.picture_one.data.save('app/static/car_pics/' + filename_one)
        #form.picture_two.data.save('app/static/car_pics/' + filename_two)
        #form.picture_three.data.save('app/static/car_pics/' + filename_three)

        #f = form.picture_one.data
        # f.save(secure_filename(f.filename))

        if form.picture_one.data:
            image_file_one = save_picture(
                form.picture_one.data, 'static/car_pics')

        if form.picture_two.data:
            image_file_two = save_picture(
                form.picture_two.data, 'static/car_pics')

        if form.picture_three.data:
            image_file_three = save_picture(
                form.picture.data, 'static/car_pics')

        car = Vehicles(
            make_id=int(makeId),
            model_id=int(modId),
            price=int(price),
            year=int(form.year.data),
            color=str(form.color.data),
            description=str(form.description.data),
            pictures=str(picture_folder),
            mileage=int(form.mileage.data),
            fuel_type=str(form.fuel_type.data),
            gear_type=str(form.gear_type.data),
            popular=str("false"),
        )
        db.session.add(car)
        db.session.commit()

        if form.trade.data:
            trade = Trade(
                user_id=int(current_user.get_id()),
                trade_amount=int(price),
            )
            db.session.add(trade)
            db.session.commit()
            flash('You have successfuly selected to trade in your vehicle, your trade will automatically be applied to your purchase', 'success')
            return redirect(url_for('main.trade_in'))

        if form.sell.data:
            flash('You have successfuly selected to sell your vehicle. The amount we will offer you is: ' + price, 'success')
            return redirect(url_for('main.sell'))

        return redirect(url_for('main.trade_in'))

Website/app/templates/base.html
{% extends "bootstrap/base.html" %} {% block title %} {{ title }} / CarSell
{%endblock %} {% block styles %} {{ super() }}
<link
  href="{{url_for('static', filename='css/styles.css')}}"
  rel="stylesheet"
/>
<link
  rel="shortcut icon"
  href="{{ url_for('static', filename='favicon.ico') }}"
/>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
  rel="stylesheet"
/>

{% endblock %} {% block navbar%}

<a href=" {{ url_for('main.index') }}" class="sidenav-logo">
  <img
    src="{{ url_for('static', filename='logo_nav.png') }}"
    id="logo"
    height="70"
    width="70"
  />
  <img
    src="{{ url_for('static', filename='text_logo.png') }}"
    id="text"
    height="30"
    width="145"
  />
</a>
<nav class="sidenav">
  <a href=" {{ url_for('main.index') }}">home</a>

  <a href="{{ url_for('main.viewAllCars') }}">cars</a>

  <a href="{{ url_for('main.allReviews') }}">car reviews</a>

  <a href="{{ url_for('main.insurance') }}">car insurance</a>

  <a href="{{ url_for('main.trade_in') }}">trade in</a>

  <a href="{{ url_for('main.FAQs') }}">faq</a>

  <a href="{{ url_for('main.contact') }}">contact us</a>

  {%if current_user.is_authenticated%} {% if current_user.admin %}
  <a href="{{ url_for('auth.admin') }}" id="auth-complete">admin</a>
  {% endif %}
  <a href="{{ url_for('auth.logout') }}" id="logout">logout</a>
  {% else %}
  <a href="{{ url_for('auth.login') }}" id="auth">login</a>
  {% endif %}
</nav>

{% endblock %} {% block content %}
<div class="container">
  {% with messages = get_flashed_messages(with_categories=true) %} {% if
  messages %} {% for category, message in messages %}
  <div class="alert alert-{{ category }} text-center">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">
      <span aria-hidden="true">&times;</span>
    </a>
    {{ message }}
  </div>
  {% endfor %} {% endif %} {% endwith %}

  <div class="row">
    {# application content needs to be provided in the app_content block #} {%
    block app_content %}{% endblock %}
  </div>
</div>

<div id="footer" class="footer">
  <p class="text-muted text-center">
    &copy;
    <script>
      document.write(new Date().getFullYear());
    </script>
    , CarSell
  </p>
</div>

{% endblock %} {% block scripts %} {{ super() }}

<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "Example Company",
    "hasMap": "https://goo.gl/maps/K6HRevCC2m82QTbF8"
  }
</script>

<script>
  $(document).ready(function () {
    $('[data-toggle="tooltip"]').tooltip();
  });
</script>

<script>
  $(".carousel").swipe({
    swipe: function (
      event,
      direction,
      distance,
      duration,
      fingerCount,
      fingerData
    ) {
      if (direction == "left") $(this).carousel("next");
      if (direction == "right") $(this).carousel("prev");
    },
    allowPageScroll: "vertical",
  });
</script>

<script>
  var coll = document.getElementsByClassName("collapsible");
  var i;

  for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function () {
      this.classList.toggle("pressed");
      var collapsibleBody = this.nextElementSibling;
      if (collapsibleBody.style.maxHeight) {
        collapsibleBody.style.maxHeight = null;
      } else {
        collapsibleBody.style.maxHeight = collapsibleBody.scrollHeight + "px";
      }
    });
  }
</script>

<script>
  const selected = document.querySelector(".selected");
  const optionsContainer = document.querySelector(".options-container");
  const optionsList = document.querySelectorAll(".option");

  selected.addEventListener("click", () => {
    optionsContainer.classList.toggle("active");
  });
  
  optionsList.forEach((o) => {
    o.addEventListener("click", () => {
      selected.innerHTML = o.querySelector("label").innerHTML;
      optionsContainer.classList.remove("active");
    });
  });
</script>

{% endblock %}

Website/app/templates/cars.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} 
{% block app_content %}
    <div class="row fade-in-content">
        {% for car in cars %}
        <div class="car-box">
            <img class="car-pic"
            src="{{ url_for('static', filename='car_pics/' + car.pictures + '/1.jpg') }}">
            <p>Make: {{make.get(car.make_id)}}</p>
            <p>Model: {{model.get(car.model_id)}}</p>
            <p>Reg. year: {{car.year}}</p>
            <p>Mileage: {{car.mileage}}</p>
            <p>Price: £{{car.price}}</p>
        </div>
        {% endfor %}
    </div>

{% endblock %}

Website/app/templates/checkout.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
	<div class="container">
		<form class="checkout form form-horizontal" method="post" role="form">
			{{ form.hidden_tag() }}
			{{ wtf.form_errors(form, hiddens="only") }}

			<h2 style="text-align:center;"> Checkout </h2>

			<div class="personal-details">
				<h3> Contact Details </h3>
				{{wtf.form_field(form.name)}}
				{{wtf.form_field(form.email)}}
				{{wtf.form_field(form.contactNumber)}}

				<br>

				<h3> Address </h3>
				{{wtf.form_field(form.address_one)}}
				{{wtf.form_field(form.address_two)}}
				{{wtf.form_field(form.city)}}
				{{wtf.form_field(form.postcode)}}
			</div>
			<div class="card-details">
				<br>
				{% for t in trading %}
					{% if t.user_id == current_user.id %}
							<h3> Total to pay: £{{car.price}} - £{{t.trade_amount}} </h3>
					{% endif %}
				{% endfor %}
		
				<h4> Please enter payment details </h4>
				{{wtf.form_field(form.cardNum)}}
				{{wtf.form_field(form.expDate)}}
				{{wtf.form_field(form.csv)}}
			</div>

			<br>

			<div class="rounded_btn_div">
				{{wtf.form_field(form.submit, class="rounded_btn")}}
			</div>

		</form>
	</div>
{% endblock %}

Website/app/templates/index.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} 
{% block app_content %}
  
<div class="row fade-in-content">
  <div class="index-upper">
    <img src="{{ url_for('static', filename='index_pic.png') }}" id="index_pic"/>
    <div class="search-form-box" id="bold-header-text">
      <form class="search-form" method="POST" action="{{ url_for('main.viewSearchedCars') }}">
        
        <div class="search-field" id="make">
          <label for="make"><h1 class="in-field-text">Make</h1></label>
          <div class="select-box-content">
            <select class="select-box" name="make" id="make">
              <option class="option" name="any">any</option>
              {% for get in makes %}
              <option class="option" name="{{get.make_name}}"> {{get.make_name}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        
        
        <div class="search-field" id="model">
          <label for="model"><h1 class="in-field-text">Model</h1></label>   
          <div class="input-box">
            <input class="text-input-box" type="text" id="model" name="model" autocomplete="off"/>
          </div>
        </div>
        
        <div class="search-field" id="color">
          <label for="color"><h1 class="in-field-text">Color</h1></label>  
          <div class="input-box">
            <input class="text-input-box" type="text" id="color" name="color" autocomplete="off"/>
          </div>
        </div>
        
        <div class="search-field" id="registration">
          <label for="registration_1"><h1 class="in-field-text">Registration</h1>from</label>  
          <select class="select-box" name="registration_1" id="registration_1">
            <option class="option" name="reg" #id="0"></option>
            {% for y in range(2022,1941,-1) %}
            <option class="option" name="reg" #id="{{y}}">{{y}}</option>
            {% endfor %}
          </select>
          <label for="registration_2">to</label>  
          <select class="select-box" name="registration_2" id="registration_2">
            <option class="option" name="reg" #id="0"></option>
            {% for y in range(2022,1941,-1) %}
            <option class="option" name="reg" #id="{{y}}">{{y}}</option>
            {% endfor %}
          </select>
        </div>
        
        <div class="search-field" id="price">
          <label for="price_1"><h1 class="in-field-text">Price</h1></label>
          <label for="price_2"></label>
          <div class="input-box">
            <input type="number" step="100" id="price_1" name="price_1" min="0" autocomplete="off" placeholder="from"/>
            <input type="number" step="100" id="price_2" name="price_2" autocomplete="off" placeholder="to"/>
          </div>
        </div>
        
        <div class="search-field" id="mileage">
          <label for="mileage_1"><h1 class="in-field-text">Mileage</h1></label>
          <label for="mileage_2"></label>
          <div class="input-box">
            <input type="number" step="1000" id="mileage_1" name="mileage_1" min="0" autocomplete="off" placeholder="from"/>
            <input type="number" step="1000" id="mileage_2" name="mileage_2" autocomplete="off" placeholder="to"/>
          </div>
        </div>
        
        <button type="submit" class="search-form-btn">Search</button>
        
      </form>
    </div>
  </div>
    
    
      <div class="blog">
        {% if current_user.admin %}
          <h2 class="header-text" id="admin">Blog<a href="{{ url_for('main.newPost') }}" id="admin-new">"new"</a></h2> 
        {% else %}
          <h2 class="header-text" id="user">Blog</h2> 
        {% endif %}
        <a href="{{ url_for('main.Blog') }}" id="more" title="more">...</a>

        <div class="blog-box">
          {%for p in posts%}
            {% if p.id <= 5 %}
              <div class="story-box">
                
                {% if current_user.admin %}
                  <a href="{{ url_for('main.editPost', id = p.id) }}" 
                  class="box-edit" id="non-btn">edit</a>
                {% else %}
                  <a class="box-user" id="non-btn-hide">edit</a>
                {% endif %}

                {%if p.picture != 'default.jpg' %}
                  <div >
                    <a class="center-img" href="{{ url_for('main.getPost', id = p.id) }}">
                      <img class="blog-pic"
                      src="{{ url_for('static', filename='post_pics/' + p.picture) }}">
                    </a>
                  </div>
                  <a href="{{ url_for('main.getPost', id = p.id) }}" class="blog-title" id="non-btn">{{ p.title }}</a>
                {% else %}
                  <a href="{{ url_for('main.getPost', id = p.id) }}" class="blog-title-solo" id="non-btn">{{ p.title }}</a>
                {% endif %}
                
              </div>
            {% endif %}
          {% endfor %}
        </div>

      </div>

    <!-- INFORMATION CAROUSEL HERE -->
    <div class="container">
      <div id="information_carousel" class="carousel " data-bs-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li
            data-target="#information_carousel"
            data-slide-to="0"
            class="active"
          ></li>
          <li data-target="#information_carousel" data-slide-to="1"></li>
          <li data-target="#information_carousel" data-slide-to="2"></li>
          <li data-target="#information_carousel" data-slide-to="3"></li>


        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <img src="static/information_slide_pics/slide_one.png" />
            <div class="carousel-caption d-none d-md-block">
              <h4>Most Popular Car 2021 - Volkswagen UP! </h4>
            </div>
          </div>
          <div class="item">
            <a class="carousel-text" href="{{ url_for('main.trade_in') }}">
              <img src="static/information_slide_pics/slide_two.png" />
              <div class="carousel-caption d-none d-md-block">
                <h4>trade in your car for money off a new one</h4> 
              </div>
            </a>
          </div>
          <div class="item">
            <a class="carousel-text" href="{{ url_for('main.history') }}">
              <img src="static/information_slide_pics/slide_three.png" />
              <div class="carousel-caption d-none d-md-block">
                <h4>check vehicle history</h4>
              </div>
            </a>
          </div>
          <div class="item">
            <a class="carousel-text" href="{{ url_for('main.FAQs') }}">
              <img src="static/information_slide_pics/slide_four.png" />
              <div class="carousel-caption d-none d-md-block">
                <h4 style="color: black;">get all your questions answered</h4>
              </div>
            </a>
          </div>
        </div>

        <!-- Controls -->
        <a
          class="left carousel-control"
          href="#information_carousel"
          role="button"
          data-slide="prev"
        >
          <span
            class="glyphicon glyphicon-chevron-left"
            aria-hidden="true"
          ></span>
          <span class="sr-only">Previous</span>
        </a>
        <a
          class="right carousel-control"
          href="#information_carousel"
          role="button"
          data-slide="next"
        >
          <span
            class="glyphicon glyphicon-chevron-right"
            aria-hidden="true"
          ></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      <br />
    </div>


<!-- MOST POPULAR HERE -->
    <h3 style="text-align: center">CarSell's Most Popular</h3>
    <div class="container">
      <div class="flex-container">
        {% for car in cars %}
          {% if car.popular == "true" %}
            <div class="popular_box">
              <a href="{{ url_for('main.vehicle', id=car.id) }}">
                <img class="popular_item" src="{{ url_for('static', filename='car_pics/' + car.pictures + '/1.jpg') }}">
              </a>
              <p class="popular_text">
                {% for m in makes %}
                  {% if m.make_id == car.make_id %}
                    {{m.make_name}}
                  {% endif %}
                {% endfor %}
                {% for mod in models %}
                  {%if mod.model_id == car.model_id %}
                    {{mod.model_name}}
                  {% endif %}
                {% endfor %}
              </p>
            </div>
          {% endif %}
        {% endfor %}
      </div>
    </div>

    <br>

<!--RSS FEED HERE -->
    <div class="collapsible-rss">
      <!--make rss feed collapsible -->
      <button type="button" class="collapsible">Open Motor Authority News RSS Feed</button>
      <!-- RSS Feed -->
      <div class="tagembed-container rssFeed collapsibleBody" style=" width:100%;height:100%;overflow: auto;"><div class="tagembed-socialwall" data-wall-id="35011" view-url="https://widget.tagembed.com/35011?view">  </div> <script src="//widget.tagembed.com/embed.min.js" type="text/javascript"></script></div>
    </div>
  </div>

<!-- READING NEIGHBORHOOD NEWSLETTER -->
    <div>
      <a href="https://rva.org.uk/neighbourhood-newsletters/">
        <img class="rnn" src="static/rva_logo.png">
      </a>
    </div>

  </div>
{% endblock %}


Website/app/templates/order_overview.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
	<div class="container">
		<div class="order-overview">
			<h2 style="text-align:center;"> Order Overview </h2>
			<img class="thumbnail" src="{{ url_for('static', filename='car_pics/' + car.pictures + '/1.jpg') }}" >
			<p>{{car.year}} <span>&#8226;</span>
				{% for m in makes %}
				    {% if m.make_id == car.make_id %}
				      	{{m.make_name}}
				    {% endif %}
				{% endfor %}
				{% for mod in models %}
				    {%if mod.model_id == car.model_id %}
				        {{mod.model_name}}
				    {% endif %}
				{% endfor %}
			</p>
			<p> {{car.mileage}} miles <span>&#8226;</span> {{car.fuel_type}} <span>&#8226;</span> {{car.gear_type}} </p>
		</div>
		<div class="one-row">
			<h3>Price of car</h3>
			<h3> £{{car.price}} </h3>
		</div>
		{% for t in trading %}
			{% if t.user_id == current_user.id %}
				<div class="one-row">
					<h3>Trading Deduction</h3>
					<h3> £{{t.trade_amount}}</h3>
				</div>
			{% endif %}
		{% endfor %}

		<div class="one-row">
			<h3> Delivery Fee </h3>
			<h3> £0 </h3>
		</div>

		<br>
		<br>

		<div class="rounded_btn_div">
			<a  href="{{ url_for('main.checkout', id=car.id) }}"><button class="rounded_btn"> Checkout </button></a>
			<a href="{{ url_for('main.vehicle', id=car.id) }}"><button class="rounded_btn"> Cancel </button></a>
		</div>


	</div>
{% endblock %}

Website/app/templates/product_cart.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
	<div class="container">
		<div class="order-overview">
			<h2 style="text-align:center;"> Order Overview </h2>
			<img class="thumbnail" src="{{ url_for('static', filename='car_pics/' + car.pictures + '/1.jpg') }}" >
			<p>{{car.year}} <span>&#8226;</span>
				{% for m in makes %}
				    {% if m.make_id == car.make_id %}
				      	{{m.make_name}}
				    {% endif %}
				{% endfor %}
				{% for mod in models %}
				    {%if mod.model_id == car.model_id %}
				        {{mod.model_name}}
				    {% endif %}
				{% endfor %}
			</p>
			<p> {{car.mileage}} miles <span>&#8226;</span> {{car.fuel_type}} <span>&#8226;</span> {{car.gear_type}} </p>
		</div>
		<div class="one-row">
			<h3>Price of car</h3>
			<h3> £{{car.price}} </h3>
		</div>
		{% for t in trading %}
			{% if t.user_id == current_user.id %}
				<div class="one-row">
					<h3>Trading Deduction</h3>
					<h3> £{{t.trade_amount}}</h3>
				</div>
			{% endif %}
		{% endfor %}

		<br>
		<div class="cart-button">
			<a  href="{{ url_for('main.checkout', id=car.id) }}"><button> Checkout </button>
		</div>


	</div>
{% endblock %}