Website/app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import current_user, login_user, logout_user, login_required
from app.main.forms import ContactForm, FAQForm, DeleteQuestionForm, \
    EditQuestionForm, PostForm, EditPostForm, TradeInForm, SellDetailsForm, \
    CheckoutDetailsForm, InsuranceForm, ReviewForm
from app.models import User, FAQ, Post, Vehicles, Model, Make, Trade, Insurance, CarReview, History
from sqlalchemy.sql import func, or_
from app.funcs import save_picture
from app import db

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/index', methods=['GET', 'POST'])
def index():
    cars_for_render = Vehicles.query.order_by(Vehicles.id.asc())
    makes_for_render = Make.query.order_by(Make.make_id.asc())
    models_for_render = Model.query.order_by(Model.model_id.asc())
    posts_for_render = Post.query.order_by(Post.created_at.asc())
    return render_template('index.html', posts=posts_for_render, cars=cars_for_render, makes=makes_for_render, models=models_for_render, title='Home')


@main.route('/ContactUs', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        flash('Your message has been sent to our team', 'success')

        return redirect(url_for('main.contact'))
    return render_template('contact.html', title='Contact Us', form=form)


@main.route('/FAQ', methods=['GET', 'POST'])
def FAQs():
    questions_for_render = FAQ.query.order_by(FAQ.id.asc())
    form = FAQForm()
    if form.validate_on_submit():
        q = FAQ(
            name=form.name.data,
            question=form.question.data,
        )
        db.session.add(q)
        db.session.commit()
    return render_template('FAQ/questions.html', questions=questions_for_render, form=form, title='FAQ')


@main.route('/FAQ/view_all', methods=['GET', 'POST'])
def viewAllQuestions():
    question = FAQ.query.order_by(FAQ.id.asc())
    return render_template('FAQ/view_all.html', questions=question, title='view')


@main.route('/FAQ/view_all/vis<id>', methods=['GET', 'POST'])
@login_required
def changeVisibility(id):
    question = FAQ.query.get(id)
    if question.display == 1:
        question.display = 0
        db.session.commit()
        return redirect(url_for('main.FAQs'))
    if question.display == 0:
        question.display = 1
        db.session.commit()
        return redirect(url_for('main.FAQs'))
    return render_template('FAQ/questions.html')


@main.route('/FAQ/delete_question/<id>', methods=['GET', 'POST'])
@login_required
def delQuestion(id):
    question = FAQ.query.get(id)
    form = DeleteQuestionForm()
    if request.method == 'POST' and form.delete.data:
        db.session.delete(question)
        db.session.commit()
        flash('Question was deleted successfuly', 'success')
        return redirect(url_for('main.FAQs'))
    if form.cancel.data:
        return redirect(url_for('main.FAQs'))
    return render_template('FAQ/delete_question.html', question=question, title="Delete Question", form=form)


@main.route('/FAQ/edit_question/<id>', methods=['GET', 'POST'])
@login_required
def editQuestion(id):
    question = FAQ.query.get_or_404(id)
    form = EditQuestionForm()
    if request.method == 'GET':
        form.name.data = question.name
        form.question.data = question.question
        form.answer.data = question.answer
    elif request.method == 'POST':
        if form.update.data and form.validate_on_submit():
            question.name = request.form['name']
            question.question = request.form['question']
            question.answer = request.form['answer']
            db.session.commit()
            return(redirect(url_for('main.FAQs')))
        if form.cancel.data:
            return(redirect(url_for('main.FAQs')))
    return render_template('FAQ/edit_question.html',  question=question, title='Edit Question', form=form)


@main.route('/all_posts', methods=['GET', 'POST'])
def Blog():
    posts = Post.query.order_by(Post.id.asc())
    return render_template('blog/all_posts.html', posts=posts)


@main.route('/blog/post_page/<id>', methods=['GET', 'POST'])
def getPost(id):
    post = Post.query.get_or_404(id)
    return render_template('blog/post_page.html', post=post)


@main.route('/blog/new_post', methods=['GET', 'POST'])
@login_required
def newPost():
    form = PostForm()
    if form.validate_on_submit():
        picture = 'default.jpg'
        if form.picture.data:
            picture = save_picture(form.picture.data, 'static/post_pics')
        p = Post(
            title=form.title.data,
            caption=form.caption.data,
            picture=picture,
            user_id=current_user.get_id()
        )
        db.session.add(p)
        db.session.commit()
        return redirect(url_for('main.index'))
    if form.cancel.data:
        return redirect(url_for('main.index'))
    return render_template('blog/new_post.html', title='New Post', form=form)


@main.route('/blog/edit_post/<id>', methods=['GET', 'POST'])
@login_required
def editPost(id):
    post = Post.query.get_or_404(id)
    form = EditPostForm()
    if request.method == 'GET':
        form.title.data = post.title
        form.caption.data = post.caption
        form.picture.data = post.picture
    elif request.method == 'POST':
        if form.update.data and form.validate_on_submit():
            post.title = request.form['title']
            post.caption = request.form['caption']
            if form.picture.data:
                post.picture = save_picture(
                    form.picture.data, 'static/post_pics')
            db.session.commit()
            return(redirect(url_for('main.index')))
        if request.method == 'POST' and form.delete.data:
            db.session.delete(post)
            db.session.commit()
            return redirect(url_for('main.index'))
        if form.cancel.data:
            return(redirect(url_for('main.index')))
    return render_template('blog/edit_post.html',  post=post, title='Edit Post', form=form)


@main.route('/vehicle/<id>', methods=['GET', 'POST'])
def vehicle(id):
    vehicle_to_render = Vehicles.query.get(id)
    makes_for_render = Make.query.order_by(Make.make_id.asc())
    models_for_render = Model.query.order_by(Model.model_id.asc())
    history_for_render = History.query.order_by(History.history_id.asc())
    return render_template('vehicles/car_page.html', car=vehicle_to_render, makes=makes_for_render, models=models_for_render, history=history_for_render)


@main.route('/trade-in', methods=['GET', 'POST'])
@login_required
def trade_in():
    form = TradeInForm()
    #form.make.choices = Make.query.order_by(Make.make_id.asc())
    #form.model.choices = Model.query.order_by(Model.model_id.asc())
    if form.validate_on_submit():

        price = 1000  # use valuation to get price?

        make_exist = Make.query.filter(
            Make.make_name == form.make.data).first()
        if not make_exist:
            make_new = Make(
                make_name=form.make.data,
            )
            db.session.add(make_new)
            db.session.commit()

        newMake = Make.query.filter(Make.make_name == form.make.data).first()
        makeId = newMake.make_id

        model_exist = Model.query.filter(
            Model.model_name == form.model.data).first()
        if not model_exist:
            model_new = Model(
                model_name=form.model.data,
                make_id=makeId
            )
            db.session.add(model_new)
            db.session.commit()

        newModel = Model.query.filter(
            Model.model_name == form.model.data).first()
        modId = newModel.model_id

        picture_folder = str(form.model.data + '_' +
                             form.color.data + '_' + str(form.year.data))
        #filename_one = secure_filename(form.picture_one.data)
        #filename_two = secure_filename(form.picture_two.data)
        #filename_three = secure_filename(form.picture_three.data)
        #form.picture_one.data.save('app/static/car_pics/' + filename_one)
        #form.picture_two.data.save('app/static/car_pics/' + filename_two)
        #form.picture_three.data.save('app/static/car_pics/' + filename_three)

        #f = form.picture_one.data
        # f.save(secure_filename(f.filename))

        if form.picture_one.data:
            image_file_one = save_picture(
                form.picture_one.data, 'static/car_pics')

        if form.picture_two.data:
            image_file_two = save_picture(
                form.picture_two.data, 'static/car_pics')

        if form.picture_three.data:
            image_file_three = save_picture(
                form.picture.data, 'static/car_pics')

        car = Vehicles(
            make_id=int(makeId),
            model_id=int(modId),
            price=int(price),
            year=int(form.year.data),
            color=str(form.color.data),
            description=str(form.description.data),
            pictures=str(picture_folder),
            mileage=int(form.mileage.data),
            fuel_type=str(form.fuel_type.data),
            gear_type=str(form.gear_type.data),
            popular=str("false"),
        )
        db.session.add(car)
        db.session.commit()

        if form.trade.data:
            trade = Trade(
                user_id=int(current_user.get_id()),
                trade_amount=int(price),
            )
            db.session.add(trade)
            db.session.commit()
            flash('You have successfuly selected to trade in your vehicle, your trade will automatically be applied to your purchase', 'success')
            return redirect(url_for('main.trade_in'))

        if form.sell.data:
            flash('You have successfuly selected to sell your vehicle. The amount we will offer you is: ' + price, 'success')
            return redirect(url_for('main.sell'))

        return redirect(url_for('main.trade_in'))

Website/app/templates/FAQ/delete_question.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<div class="row fade-in-content">
    <br>
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Delete question {{question.id}} by {{question.name}}?</h3>
            </div>
            <div class="panel-body">
                {{ wtf.quick_form(form, button_map={'delete':'danger', 'cancel' : 'default'}, extra_classes="text-muted") }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

Website/app/templates/FAQ/edit_question.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<div class="row fade-in-content">
    <br>
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Edit Question</h3>
            </div>
            <div class="panel-body">
                {{ wtf.quick_form(form, button_map={'update':'success', 'cancel' : 'default'}, extra_classes="text-muted") }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

Website/app/templates/FAQ/questions.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block
app_content %}
<div class="row fade-in-content">
  <div class="faqs">
    <h2 style="text-align: center">Frequently Asked Questions</h2>
    <p style="text-align: center;">
      If the answer to your question is not below, or you want some more
      information, then send as a <a href="#query" class="clickme">question</a>
    </p>

    {% if current_user.admin %}
      <a href="{{ url_for('main.viewAllQuestions') }}" class="pull-right clickme">
        view all
      </a>
      <br />
    {% endif %} 
    {%for q in questions %} 
      {% if q.display == True %} 
        {% if current_user.admin and current_user.is_authenticated %}
          <h3 style="text-align: left">
            {{ q.question }} |
            <a href="{{ url_for('main.editQuestion', id = q.id) }}" class="clickme">
              edit
            </a>
            |
            <a
              href="{{ url_for('main.delQuestion', id = q.id) }}"
              class="text-danger clickme"
            >
              delete
            </a>
          </h3>
          <p>{{ q.answer }}</p>
        {% else %}
          <button type="button" class="collapsible">{{ q.question }}</button>
          <div class="collapsibleBody">
            <p class="collapsibleText">{{ q.answer }}</p>
          </div>
        {% endif %}
        <!--<p class="q-auth">asked by {{ q.name }}</p>-->
        <br />
      {% endif %} 
    {% endfor %}

    <h3 style="text-align: center;" id="query">Query form</h3>
    <div class="FAQuery-form">
      <div class="col-md-4 col-md-offset-4">
        <form class="form form-horizontal" method="post" role="form">
          {{ form.hidden_tag() }} 
          {{ wtf.form_errors(form, hiddens="only") }} 

          {{ wtf.form_field(form.question) }}
          {{ wtf.form_field(form.name) }} 
          <div class="rounded_btn_div">
            {{ wtf.form_field(form.submit, class="rounded_btn") }}
          </div>
        </form>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

Website/app/templates/FAQ/view_all.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block
app_content %}

<div class="row fade-in-content">
  <h1>List of all questions:</h1>
  {%for q in questions %}
  <br />
  <h3 style="text-align: left">
    {{ q.question }}
    |
    <a href="{{ url_for('main.editQuestion', id = q.id) }}" class="clickme">
      edit
    </a>
    |
    <a
      href="{{ url_for('main.delQuestion', id = q.id) }}"
      class="text-danger clickme"
    >
      delete
    </a>
    | {% if q.display %}
    <a href="{{ url_for('main.changeVisibility', id = q.id) }}" class="clickme">
      hide
    </a>
    {% else %}
    <a href="{{ url_for('main.changeVisibility', id = q.id) }}" class="clickme">
      show
    </a>
    {% endif %}
  </h3>
  <p>{{ q.answer }}</p>
  <p class="q-auth">asked by {{ q.name }}</p>
  <hr style="background-color: rgb(75, 75, 75)" />
  <br />
  {% endfor %}
</div>
{% endblock %}